### ISSUE TITLE
No puedo pushear los cambios necesarios para aceptar una pull request

### ISSUE THREAD

**Issue by ArturoAlvarezz** [GbustarrOrg/TusunamiBank#25]
Se necesitaba cambiar cosas en el codigo de Rafael para aceptar su pull request, y al hacer los cambios he intentar pushearlos para que luego se actualice la pull request, da el error de la imagen
![image](https://github.com/GbustarrOrg/TusunamiBank/assets/60265365/01424ae7-8762-45cc-9fef-6d05c8944d13)

**Comment by ArturoAlvarezz** [comment]
https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch

**Comment by Gbustarr** [comment]
Te he cambiado el rol a mantenedor, revisa si ya puedes hacer los cambios

**Comment by ArturoAlvarezz** [comment]
Gracias mi reyyyyyyy
